// shoes-frontend/src/pages/Home.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ArrowRight, Search } from 'lucide-vue-next';
import ClientLayout from '../layouts/ClientLayout.vue';
import { useLanguage } from '../i18n';
import { useCategories } from '../stores/categories';
import { useProducts } from '../stores/products';
import { resolveProductImage } from '../utils/api';
import heroFactoryImage from '../assets/home-shoe-factory-hero.png';

const router = useRouter();
const searchId = ref('');
const { t, langObj } = useLanguage();
const { categories, getCategoryName } = useCategories();
const { products } = useProducts();
const buyers = computed(() => langObj.value.home.buyers as readonly string[]);
const firstCategoryPath = computed(() => categories.value[0] ? `/products?category=${categories.value[0].id}` : '/products');
const homeProducts = computed(() => products.value.filter((product) => product.featured).slice(0, 20));

const handleSearch = () => {
  if (searchId.value.trim()) {
    router.push(`/products?search=${encodeURIComponent(searchId.value.trim())}`);
  }
};
</script>

<template>
  <ClientLayout>
    <section class="relative flex min-h-[500px] w-full items-center overflow-hidden bg-white md:min-h-[600px]">
      <div class="absolute inset-0 z-0">
        <div class="absolute right-0 top-0 h-full w-full md:w-[60%]">
          <img
            :src="heroFactoryImage"
            alt="Bright modern shoe factory production line"
            class="h-full w-full object-cover object-center"
          />
        </div>
        <div class="absolute inset-0 z-10 hidden bg-gradient-to-r from-white via-white/80 to-transparent md:block" />
        <div class="absolute inset-0 z-10 bg-gradient-to-t from-white via-white/60 to-transparent md:hidden" />
      </div>

      <div class="relative z-20 mx-auto w-full max-w-7xl px-6 py-20 md:py-0">
        <div class="flex w-full flex-col justify-center md:w-[55%]">
          <div class="mb-8 inline-flex items-center gap-2 self-start rounded-full border border-blue-100 bg-blue-50 px-3 py-1">
            <span class="h-1.5 w-1.5 animate-pulse rounded-full bg-blue-600" />
            <span class="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">{{ t('home.direct') }}</span>
          </div>

          <h1 class="mb-8 text-5xl font-extrabold leading-[1.1] tracking-tight text-gray-900 md:text-7xl">
            {{ t('home.slogan1') }}<br />
            <span class="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
              {{ t('home.slogan2') }}
            </span>
          </h1>

          <div class="mt-4 md:mt-8">
            <h3 class="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-gray-400">{{ t('home.serve') }}</h3>
            <div class="flex flex-wrap gap-3">
              <div
                v-for="audience in buyers"
                :key="audience"
                class="flex items-center rounded-xl border border-gray-100 bg-white px-5 py-2.5 text-sm font-medium text-gray-700 shadow-[0_2px_10px_rgb(0,0,0,0.04)] transition-transform hover:-translate-y-0.5"
              >
                <div class="mr-2.5 h-1.5 w-1.5 rounded-full bg-gray-300 rtl:ml-2.5 rtl:mr-0" />
                {{ audience }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="mx-auto my-12 max-w-7xl px-4 md:px-6">
      <div class="mx-auto max-w-2xl">
        <form class="relative flex items-center" @submit.prevent="handleSearch">
          <Search class="absolute left-4 h-5 w-5 text-gray-400 rtl:left-auto rtl:right-4" />
          <input
            v-model="searchId"
            type="text"
            :placeholder="t('home.searchPlaceholder')"
            class="w-full rounded-full border border-gray-200 bg-white py-4 pl-12 pr-32 text-sm shadow-sm transition-all focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100 md:text-base rtl:pl-32 rtl:pr-12"
          />
          <button type="submit" class="absolute bottom-2 right-2 top-2 rounded-full bg-gray-900 px-6 text-sm font-medium text-white transition-colors hover:bg-gray-800 rtl:left-2 rtl:right-auto">
            {{ t('home.searchAction') }}
          </button>
        </form>
      </div>
    </section>

    <section class="mx-auto max-w-7xl px-4 pb-20 md:px-6">
      <div class="mb-8 flex items-center justify-between">
        <h2 class="text-2xl font-bold text-gray-900">{{ t('home.featuredProducts') }}</h2>
      </div>

      <div v-if="homeProducts.length" class="grid grid-cols-2 gap-4 md:grid-cols-3 md:gap-6 lg:grid-cols-5">
        <RouterLink
          v-for="product in homeProducts"
          :key="product.id"
          :to="`/product/${product.id}`"
          class="group flex flex-col overflow-hidden rounded-xl border border-gray-100 bg-white transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_8px_30px_rgb(0,0,0,0.08)]"
        >
          <div class="relative aspect-[4/5] overflow-hidden bg-gray-50">
            <img :src="resolveProductImage(product.images)" :alt="product.id" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" loading="lazy" />
          </div>
          <div class="flex flex-grow flex-col p-4 text-center lg:text-left rtl:lg:text-right">
            <p class="mb-1 font-mono text-xs text-gray-400">{{ product.id }}</p>
            <h3 class="mb-1 line-clamp-1 text-sm font-medium text-gray-900">
              {{ t('products.newProduct', { cat: getCategoryName(product.category), style: product.brief }) }}
            </h3>
            <div class="mt-auto hidden items-center justify-center rounded-md border border-gray-200 py-2 text-xs font-medium text-gray-700 transition-colors group-hover:border-gray-900 group-hover:bg-gray-900 group-hover:text-white lg:flex">
              {{ t('home.viewDetails') }}
            </div>
          </div>
        </RouterLink>
      </div>
      <div v-else class="rounded-xl border border-dashed border-gray-200 bg-white py-16 text-center text-sm text-gray-500">
        暂无首页精选产品
      </div>

      <div class="mt-16 text-center">
        <RouterLink :to="firstCategoryPath" class="inline-flex items-center justify-center gap-2 rounded-full border border-gray-300 bg-white px-8 py-4 text-sm font-medium text-gray-700 transition-all hover:bg-gray-50 hover:text-gray-900">
          {{ t('home.viewAll') }}
          <ArrowRight class="h-4 w-4 rtl:rotate-180" />
        </RouterLink>
      </div>
    </section>
  </ClientLayout>
</template>

// shoes-frontend/src/pages/Home.tsx
import { useState, FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Search, ArrowRight } from 'lucide-react';
import { products, categories } from '../data';
import ClientLayout from '../layouts/ClientLayout';
import { useLanguage } from '../i18n';

export default function Home() {
  const navigate = useNavigate();
  const [searchId, setSearchId] = useState('');
  const homeProducts = products.slice(0, 20);
  const { t, langObj } = useLanguage();

  const handleSearch = (e: FormEvent) => {
    e.preventDefault();
    if (searchId.trim()) {
      navigate(`/products?search=${searchId.trim()}`);
    }
  };

  return (
    <ClientLayout>
      {/* Premium Hero Section - Apple Style */}
      <section className="relative w-full min-h-[500px] md:min-h-[600px] bg-white overflow-hidden flex items-center">
        {/* Background Image / Split */}
        <div className="absolute inset-0 z-0">
          <div className="absolute top-0 right-0 w-full md:w-[60%] h-full">
            <img 
              src="https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2000&auto=format&fit=crop" 
              alt="Premium Shoes"
              className="w-full h-full object-cover object-center"
            />
          </div>
          {/* Gradients to blend image with solid color */}
          <div className="absolute inset-0 bg-gradient-to-r from-white via-white/95 to-transparent z-10 hidden md:block"></div>
          <div className="absolute inset-0 bg-gradient-to-t from-white via-white/80 to-transparent z-10 md:hidden"></div>
        </div>
        
        <div className="relative z-20 max-w-7xl mx-auto px-6 w-full py-20 md:py-0">
          <div className="w-full md:w-[55%] flex flex-col justify-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-100 mb-8 self-start">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-600 animate-pulse"></span>
              <span className="text-xs font-bold tracking-[0.2em] text-blue-600 uppercase">{t('home.direct')}</span>
            </div>
            
            <h1 className="text-5xl md:text-7xl font-extrabold text-gray-900 tracking-tight leading-[1.1] mb-8">
              {t('home.slogan1')}<br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">
                {t('home.slogan2')}
              </span>
            </h1>
            
            <div className="mt-4 md:mt-8">
              <h3 className="text-xs font-bold text-gray-400 mb-5 tracking-[0.2em] uppercase">{t('home.serve')}</h3>
              <div className="flex flex-wrap gap-3">
                {(langObj.home.buyers as string[]).map((audience, i) => (
                  <div key={i} className="px-5 py-2.5 bg-white shadow-[0_2px_10px_rgb(0,0,0,0.04)] border border-gray-100 rounded-xl text-sm font-medium text-gray-700 flex items-center transition-transform hover:-translate-y-0.5">
                    <div className="w-1.5 h-1.5 rounded-full bg-gray-300 mr-2.5 ltr:mr-2.5 rtl:ml-2.5 rtl:mr-0"></div>
                    {audience}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Global Search Section */}
      <section className="max-w-7xl mx-auto px-4 md:px-6 my-12">
        <div className="max-w-2xl mx-auto">
          <form onSubmit={handleSearch} className="relative flex items-center">
            <Search className="absolute left-4 rtl:right-4 rtl:left-auto w-5 h-5 text-gray-400" />
            <input 
              type="text" 
              value={searchId}
              onChange={(e) => setSearchId(e.target.value)}
              placeholder={t('home.searchPlaceholder')} 
              className="w-full pl-12 pr-32 rtl:pr-12 rtl:pl-32 py-4 rounded-full border border-gray-200 bg-white shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-500 transition-all text-sm md:text-base"
            />
            <button 
              type="submit"
              className="absolute right-2 rtl:left-2 rtl:right-auto top-2 bottom-2 px-6 bg-gray-900 text-white rounded-full text-sm font-medium hover:bg-gray-800 transition-colors"
            >
              {t('home.searchAction')}
            </button>
          </form>
        </div>
      </section>

      {/* Products Grid */}
      <section className="max-w-7xl mx-auto px-4 md:px-6 pb-20">
        <div className="flex items-center justify-between mb-8">
          <h2 className="text-2xl font-bold text-gray-900">{t('home.featuredProducts')}</h2>
        </div>

        {/* 5 cols on desktop, 2 cols on mobile */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 md:gap-6">
          {homeProducts.map((product) => (
             <Link 
              key={product.id} 
              to={`/product/${product.id}`}
              className="group bg-white rounded-xl overflow-hidden border border-gray-100 transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_8px_30px_rgb(0,0,0,0.08)] flex flex-col"
            >
              <div className="aspect-[4/5] overflow-hidden bg-gray-50 relative">
                <img 
                  src={product.images[0]} 
                  alt={product.id}
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  loading="lazy"
                />
              </div>
              <div className="p-4 flex flex-col flex-grow text-center lg:text-left rtl:lg:text-right">
                <p className="text-xs font-mono text-gray-400 mb-1">{product.id}</p>
                <h3 className="text-sm font-medium text-gray-900 line-clamp-1 mb-1">{t('products.newProduct', { cat: t(`categories.${product.category}`), style: product.brief })}</h3>
                <div className="mt-auto hidden lg:flex items-center justify-center py-2 border border-gray-200 rounded-md text-xs font-medium text-gray-700 group-hover:bg-gray-900 group-hover:text-white group-hover:border-gray-900 transition-colors">
                  {t('home.viewDetails')}
                </div>
              </div>
            </Link>
          ))}
        </div>

        <div className="mt-16 text-center">
          <Link 
            to={`/products?category=${categories[0].id}`}
            className="inline-flex items-center justify-center px-8 py-4 border border-gray-300 rounded-full text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 hover:text-gray-900 transition-all gap-2"
          >
            {t('home.viewAll')}
            <ArrowRight className="w-4 h-4 rtl:rotate-180" />
          </Link>
        </div>
      </section>
    </ClientLayout>
  );
}
